# Generated by Django 5.0.7 on 2024-07-26 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='トッピング名')),
                ('price', models.IntegerField(verbose_name='価格')),
            ],
            options={
                'verbose_name': 'トッピング',
                'verbose_name_plural': 'トッピング',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='テーブル番号')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_order.item', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
            },
        ),
        migrations.CreateModel(
            name='ToppingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_orders', to='self_order.order', verbose_name='注文')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_order.topping', verbose_name='トッピング')),
            ],
            options={
                'verbose_name': 'トッピング注文',
                'verbose_name_plural': 'トッピング注文',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, through='self_order.ToppingOrder', to='self_order.topping', verbose_name='トッピング'),
        ),
    ]
